config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Product Routes
  get 'admin_approved_products', to: 'products#admin_approved_products'
  get 'products/:id/responded', to: 'products#responded', as: 'responded' #Product owner to see the list of interested buyers
  get '/search_results', to: 'products#searched_products'
  resources :products do
    member do
      patch :buy    # Ajax to handle the buy now button feature
      patch :toggle_is_approved   # Admin to approve or reject the product ad created
    end
    # Reviews routes
    resources :reviews, only: %i[create destroy]
  end
  resources :reviews, only: [:index] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  # Categories
  resources :categories

  # User signup and login
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # User admin
  get 'admin', to: 'users#admin'
  
  # Password Reset
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Login with google
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  # Conversations and Messages
  resources :conversations do
    resources :messages
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  after_create :welcome
  
  has_many :products, dependent: :destroy
  has_many :conversations, dependent: :destroy
  has_many :messages, dependent: :destroy

  paginates_per 5
  
  validates :username, presence: true,
                    length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                     
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  has_secure_password
  
  def self.digest(string)
    if ActiveModel::SecurePassword.min_cost 
      cost = BCrypt::Engine::MIN_COST
    else
      cost = BCrypt::Engine.cost
    end
    BCrypt::Password.create(string, cost: cost)
  end

  def welcome
    WelcomeMailer.with(user: @user).delay.welcome_email
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_user, except: %i[edit update index]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: %i[admin destroy]

  def index
    @users = User.page(params[:page])
  end

  def show
    @products = @user.products
    @conversation = Conversation.new
    @conversations = Conversation.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to My Market #{@user.username}, you signed up successfully"
      redirect_to admin_approved_products_path
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Account is successfully updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = 'Account and all the associated ads are succesfully deleted'
    redirect_to admin_approved_products_path
  end

  def admin; end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    if current_user != @user
      flash.now[:alert] = 'You are not authoruized to do this actions. You can only edit or update your own account'
      redirect_to root_path
    end
  end
end

app/views/users/_form.html.erb
<div class="row justify-content-center">
    <div class="col-10">

        <%= render 'shared/errors', obj: @user %>

        <%= form_with(model: @user, class: "shadow p-3 mb-3 rounded", id: "form_temp", local: true, data: { turbo: false } ) do |f| %>
            
            <div class="form-group row">
                <%= f.label :username, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.text_field :username, class: "form-control", placeholder: "Enter your Username" %>
                </div>
            </div>
            <br/>
            <div class="form-group row">
                <%= f.label :email, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.email_field :email, class: "form-control", placeholder: "Enter your Email" %>
                </div>
            </div>
            <br/>
            <% if @user.new_record? %>
                <div class="form-group row">
                    <%= f.label :password, class: "col-2 col-form-label" %>
                    <div class="col-sm-10">
                        <%= f.password_field :password, class: "form-control", placeholder: "Enter a Password" %>
                    </div>
                </div>
            <% else %>
                <div class="text-center">
                    <%= link_to "Reset Password", password_reset_path, class: "btn btn-outline-primary" %>
                </div>
                <br/>
                <p class="text-center">OR</p>
            <% end %>
            <br/>
            <div class="text-center">
                <%= f.submit (@user.new_record? ? 'Sign up' : 'Update Account'), class: "btn btn-outline-success" %>
            </div>
        <% end %>
    </div>
    <%= link_to '[ Cancel and return to ads listing ]', admin_approved_products_path, class: "text-primary text-center" %>
</div>

app/views/users/_user.html.erb
<div> <%= link_to user.username, user %> </div>

app/views/users/admin.html.erb
<div id="page-content">
    <h1 class="text-center mt-4">Admin Dashboard</h1>
</div>

<div class="admin-container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title text-center">Users</h5>
          <p class="card-text text-center"><%= link_to 'All Users', users_path, class: "btn btn-primary admin-func-btns" %></p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title text-center">Categories</h5>
          <p class="card-text text-center"><%= link_to 'Add Category', new_category_path, class: "btn btn-primary admin-func-btns" %></p>
          <p class="card-text text-center"><%= link_to 'All Categories', categories_path, class: "btn btn-primary admin-func-btns" %></p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title text-center">Reviews</h5>
          <p class="card-text text-center"><%= link_to 'All Reviews', reviews_path, class: "btn btn-primary admin-func-btns" %></p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title text-center">Products</h5>
          <p class="card-text text-center"><%= link_to 'All Products', products_path, class: "btn btn-primary admin-func-btns" %></p>
          <p class="card-text text-center"><%= link_to 'All Approved Products', admin_approved_products_path, class: "btn btn-primary admin-func-btns" %></p>
          <p class="card-text text-center"><%= link_to 'Add Product', new_product_path, class: "btn btn-primary admin-func-btns" %></p>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="text-center">
    <%= link_to '[ Cancel and return to products listing ]', admin_approved_products_path, class: "text-primary" %>
  </div>
</div>

app/views/users/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit profile</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
    <div id="page-content">
        <h1 class="text-center mt-4">Users List</h1>
    </div>
    <%= paginate @users %>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Ads Posted</th>
            <th scope="col">Joined</th>
            <th scope="col"  colspan="3" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <td><%= user.username %></td>
                    <td><%= user.email %></td>
                    <td><%= pluralize(user.products.count, "product") %></td>
                    <td><%= time_ago_in_words(user.created_at) %></td>
                    <td><%= link_to 'Show', user_path(user) %></td>
                    <% if (logged_in? && user == current_user) || admin? %>
                        <td><%= link_to 'Edit', edit_user_path(user) %></td>
                        <td><%= link_to 'Delete',user_path(user),
                                                 method: :delete,
                                                 data: { confirm: "Are you sure you want to delete this User?" } %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
    <%= paginate @users %>
    <div class="text-center">
        [<%= link_to 'Create new ad',new_product_path %> | <%= link_to 'Home', root_path %>]
    </div>
</div>

app/views/users/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Sign up!!!</h1>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="text-center">
        <h1><%= @user.username %>'s profile</h1>

        <h3>Ads Created</h3>
        <br/>
        <div>
            <% if (logged_in? && @user == current_user) || admin? %>
                <%= link_to 'Edit profile', edit_user_path(@user), class:"btn btn-outline-primary", style: "width: 100%;" %>
                <%= link_to 'Delete profile', user_path(@user), class:"btn btn-outline-danger", style: "width: 100%;" %>
            <% end %>
        </div>
        <br/>
        <div>
            <%= link_to 'Start Conversation', conversations_path, class:"btn btn-outline-success", style: "width: 100%;" %>
        </div>
        <br/>
        <div>
            <% if current_user == @user %>
                <%= link_to 'Add Product', new_product_path, class: "btn btn-outline-primary", style: "width:100%;" %>
            <% end %>
        </div>
    </div>
    <br/>
    <%= render 'products/product' %>

    <div class="text-center">
        <%= link_to '[ Cancel and return to ads listing ]', admin_approved_products_path, class: "text-primary" %>
    </div>
</div>