config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Product Routes
  get 'admin_approved_products', to: 'products#admin_approved_products'
  get 'products/:id/responded', to: 'products#responded', as: 'responded' #Product owner to see the list of interested buyers
  get '/search_results', to: 'products#searched_products'
  resources :products do
    member do
      patch :buy    # Ajax to handle the buy now button feature
      patch :toggle_is_approved   # Admin to approve or reject the product ad created
    end
    # Reviews routes
    resources :reviews, only: %i[create destroy]
  end
  resources :reviews, only: [:index] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  # Categories
  resources :categories

  # User signup and login
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # User admin
  get 'admin', to: 'users#admin'
  
  # Password Reset
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Login with google
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  # Conversations and Messages
  resources :conversations do
    resources :messages
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  paginates_per 5
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]
  skip_before_action :require_user, only: %i[index show]
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.page(params[:page])
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page])
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category added successfully!'
      redirect_to categories_path
    else
      flash.now[:alert] = "Something went wrong. Couldn't add category. Try again"
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category updated!'
      redirect_to categories_path
    else
      render 'edit'
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category removed!'
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/views/categories/_form.html.erb
<div class="row justify-content-center">
    <div class="col-10">
        <%= form_with(model: @category,  class: "shadow p-3 mb-3 rounded", id: "form_temp", local: true) do |f| %>
            <div class="form-group row">
                <%= f.label :Name, class: "col-sm-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.text_field :name, class: "form-control", placeholder: "Enter Category Name" %>
                </div>
            </div>
            <br/>
            <div class="text-center">
                <%= f.submit (@category.new_record? ? "Add Category" : "Update Category"), class: "btn btn-outline-success" %>
            </div>
        <% end %>
    </div>
    <%= link_to '[ Cancel and return to products listing ]', admin_approved_products_path, class: "text-primary text-center" %>
    <%= link_to '[ All Categories ]', categories_path, class: "text-primary text-center" %>
</div>

app/views/categories/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit Category</h1>
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
    <div id="page-content">
        <h1 class="text-center mt-4">All Categories</h1>
    </div>
    <%= paginate @categories %>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
            <th scope="col">Category Name</th>
            <th scope="col"  colspan="3" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @categories.each do |category| %>
                <tr>
                    <td><%= category.name %></td>
                    <td><%= link_to 'Show', category_path(category) %></td>
                    <% if admin? %>
                        <td><%= link_to 'Edit', edit_category_path(category) %></td>
                        <td><%= link_to 'Delete', category_path(category),
                            method: :delete,
                            data: { confirm: "Are you sure you want to delete this category?" }  %>
                        </td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<br/>
<%= paginate @categories %>

<div class="text-center">
        <% if admin? %>
            <%= link_to 'Add Category', new_category_path, class: "btn btn-outline-success" %>
        <% end %>
</div>

app/views/categories/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Add new Category</h1>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="container">
    <h1 class="text-center">MyMarket | <%= @category.name.upcase %></h1>
        <table class="table table-bordered table-striped">
        <thead>
            <tr>
            <th scope="col">Product title</th>
            <th scope="col">Product price</th>
            <th scope="col"  colspan="1" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <%= paginate @products %>
            <% @category.products.each do |p| %>
                <tr>
                    <td><%= p.title %></td>
                    <td><%= p.price %></td>
                    <td><%= link_to "View Product", product_path(p) %></td>
                </tr>
            <% end %>
            <%= paginate @products %>
        </tbody>
    </table>
</div>