config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Product Routes
  get 'admin_approved_products', to: 'products#admin_approved_products'
  get 'products/:id/responded', to: 'products#responded', as: 'responded' #Product owner to see the list of interested buyers
  get '/search_results', to: 'products#searched_products'
  resources :products do
    member do
      patch :buy    # Ajax to handle the buy now button feature
      patch :toggle_is_approved   # Admin to approve or reject the product ad created
    end
    # Reviews routes
    resources :reviews, only: %i[create destroy]
  end
  resources :reviews, only: [:index] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  # Categories
  resources :categories

  # User signup and login
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # User admin
  get 'admin', to: 'users#admin'
  
  # Password Reset
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Login with google
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  # Conversations and Messages
  resources :conversations do
    resources :messages
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include Filterable
  belongs_to :user
  belongs_to :category

  paginates_per 3

  has_many :reviews, dependent: :destroy
  has_many_attached :pictures, dependent: :destroy

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  validates :price, presence: true, numericality: true
  validates :city, presence: true
  validates :phone_number, presence: true, numericality: true
  
  scope :filter_by_title, ->(title) { where('lower(title) LIKE ?', "%#{title}%") }
  scope :filter_by_category, ->(category_id) { where category_id: category_id }
  scope :filter_by_city, ->(city) { where('lower(city) LIKE ?', "%#{city}%") }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy buy responded]
  before_action :require_same_user_or_admin, only: %i[edit update destroy responded]
  before_action :set_categories
  before_action :require_admin, only: %i[index toggle_is_approved]
  skip_before_action :require_user, only: %i[show admin_approved_products]

  def index
    # Only admin has the access to see all created ads in order to approve or reject the posted ad
    @products = Product.page(params[:page]).per(5)
  end

  def show
    @reviews = @product.reviews.all
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      flash[:notice] = 'Ad created successfully.Waiting for Admin approval'
      redirect_to admin_approved_products_path
    else
      render 'new'
    end
  end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Ad updated successfully'
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_approved_products_path
  end

  def toggle_is_approved
    @product = Product.find(params[:id])
    admin = current_user.username
    @product.update!(is_approved: true, approved_by: admin)
    redirect_to admin_approved_products_path, notice: 'The Product is successfully approved'
  end

  def admin_approved_products
    # Once admin has approved the posted ad, the product will be visible to regular user
    @products = Product.page(params[:page])
  end

  def buy
    # This action handles the situation after the user clicks 'Buy now' button
    @user = User.find(params[:user_id])
    ProductResponseMailer.with(user: @user).delay.response(@product)
    @product.responsed_user_ids.push(@user.id)
    if @product.save
      redirect_to product_path(@product), notice: 'You have successfully responded. Seller will contact you soon'
    else
      flash.now[:alert] = 'Something went wrong.Try again...'
    end
  end

  def responded
    # This action handles the situation where the seller can see the list of interested buyers
    @product.responsed_user_ids.each do |u|
      @user = User.find(u)
    end
  end

  def searched_products
    # This action handles the filter feature where results get rendered in different view named same as this action
    @products = Product.filter(params.slice(:title, :category, :city)).page(params[:page])
    if @products.count.zero?
      redirect_to admin_approved_products_path, alert: 'No results found matching your search'
    else
      flash.now[:notice] = "#{@products.count} results found matching your search"
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id, :city, :phone_number, :image, pictures: [])
  end

  def require_same_user_or_admin
    if current_user != @product.user && !admin?
      flash[:alert] = 'You can only edit or delete your own posted ads'
      redirect_to @product
    end
  end

  def set_categories
    @categories = Category.all.order(:name)
  end
end

app/views/products/_form.html.erb
<%= render 'shared/errors', obj: @product %>


<div class="row justify-content-center">
    <div class="col-10">
        <%= form_with(model: @product,  class: "shadow p-3 mb-3 rounded", id: "form_temp", local: true, data: { turbo: false } ) do |f| %>
            <div class="form-group row">
                <%= f.label :title, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
                </div>
            </div>
            <br/>
            <div class="form-group row">
                <%= f.label :description, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.text_area :description, class: "form-control", placeholder: "Description of the product" %>
                </div>
            </div>
            <br/>
            <div class="form-group row">
                <%= f.label :price, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                   <%= f.text_field :price, class: "form-control", placeholder: "Enter price of the product" %>
                </div>
            </div>
            <br/>

            <div class="form-group row">
                <%= f.label :category, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})%>
                </div>
            </div>
            <br/>
            <div class="form-group row">
                <%= f.label :city, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.text_field :city, class: "form-control", placeholder: "Enter the name of City" %>
                </div>
            </div>
            <br/>
            <div class="form-group row">
                <%= f.label :phone_number, class: "col-2 col-form-label" %>
                <div class="col-sm-10">
                    <%= f.text_field :phone_number, class: "form-control", placeholder: "Enter your Phone number" %>
                </div>
            </div>
            <br/>
            <div class="form-group row">
            <%= f.label :pictures, class: "col-2 col-form-label" %>
            <div class="col-sm-10">
                <%= f.file_field :pictures, class: "form-control", multiple: true %>
                <p class="text-secondary">First picture will be displayed as the thumbnail in the all products page</p>
            </div>
            </div>
            <br/>
            <div class="text-center">
                <%= f.submit (@product.new_record? ? "Create Ad" : "Update Ad"), class: "btn btn-outline-success" %>
            </div>
        <% end %>
    </div>
    <%= link_to '[ Cancel and return to products listing ]', admin_approved_products_path, class: "text-primary text-center" %>
</div>

app/views/products/_notify.html.erb
<% if !logged_in? %>
    <p class="text-center bg-warning">You must be logged in to <strong>Buy</strong> any product or <strong>Add any Reviews</strong>.
    Click here to <%= link_to 'Login now', login_path, class: "btn btn-outline-dark" %></p>
<% end %>

app/views/products/_product.html.erb
<% if @products.count == 0 %>
    <h2 class="text-secondary text-center">No Products available... Create one now by clicking on
      <%= link_to 'Create new Product',new_product_path %></h2>
<% end %>
<% @products.each do |p| %>
  <% if p.is_approved == true %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card h-100 text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            Ad posted by <%= p.user.username %> 
          </div>
          <%= image_tag p.pictures.first, class: "img-thumbnail card-image-top", style: "height: 25rem" if p.pictures.present? %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to p.title, product_path(p), class: "text-success" %></h5>
            <p class="card-text">Rs. <%= p.price %></p> 
            <p class="card-text"><%= link_to p.category.name, p.category %></p> 
            <% if p.responsed_user_ids.include?(current_user) %>
              <p class="card-text text-danger">You Have responded</p>
            <% end %>
            <%= link_to "View", product_path(p), class: "btn btn-outline-success" %>
            <% if (logged_in? && p.user == current_user) || admin? %>
              <%= link_to "Edit", edit_product_path(p), class: "btn btn-outline-info" %>
              <%= link_to "Delete", product_path(p), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %></p>
              <%= link_to 'Responded Users', responded_path(p), class: "btn btn-warning" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(p.created_at) %> ago, 
            edited <%= time_ago_in_words(p.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/products/admin_approved_products.html.erb
<%= render 'notify' %>
    
    <div class="container">
        <div id="page-content">
            <h1 class="text-center mt-4">All Products</h1>
        </div>
    <%= paginate @products %>
    <div>
    <%= render 'product' %>
    </div>
    <br/>
    <%= paginate @products %>
    </div>

app/views/products/edit.html.erb
<<div id="page-content">
<h1 class="text-center mt-4">Edit Ad</h1>
<%= render 'form' %>
</div>

app/views/products/index.html.erb
    <div class="container">
    <h2 class="text-center">Products waiting to be approved</h2>
    <%= paginate @products %>
    <table class="table table-bordered">
        <thead>
            <tr>
            <th scope="col">product_id</th>
            <th scope="col">Product Title</th>
            <th scope="col">Price</th>
            <th scope="col">Ad Posted By</th>
            <th scope="col">Admin approval</th>
            </tr>
        </thead>
      <tbody>
        <% @products.each do |p| %>
                <tr>
                    <td><%= p.id %></td>
                    <td><%= p.title %></td>
                    <td><%= p.price %></td>
                    <td><%= p.user.username %></td>
                    <% if p.is_approved ==false %>
                        <td id="<%= dom_id(p) %>"><%= link_to 'Approve',
                        toggle_is_approved_product_path(id: p.id), remote: true, method: :patch,
                        class: "btn btn-#{ p.is_approved ? 'warning' : 'success'}",
                        data: { confirm: "Are you sure you want to approve this Product ?" } %> | 
                        <%= link_to "Reject", product_path(id: p.id), class: "btn btn-outline-danger",
                        method: :delete, data: { confirm: "Are you sure you want to reject this product?" } %></td>
                    <% else %>
                        <td>Approved by Admin (<%= p.approved_by %>)</td>
                    <% end %>
                </tr>
            <% end %>
      </tbody>
    </table>
    <%= paginate @products %>
</div>

app/views/products/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create a new Ad</h1>
  <%= render 'form' %>
</div>

app/views/products/responded.html.erb
<div class="container">
    <div id="page-content">
        <h1 class="text-center mt-4">Responded Users List</h1>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col"  colspan="2" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @product.responsed_user_ids.each do |u| %>
                <% @user = User.find(u) %>
                <tr>
                    <td><%= @user.username %></td>
                    <td><%= @user.email %></td>
                    <td><%= link_to 'Show', user_path(@user) %></td>
                    <% if (logged_in? && @user == current_user) || admin? %>
                        <td><%= link_to 'Edit', edit_user_path(@user) %></td>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="text-center">
        [<%= link_to 'Create new ad',new_product_path %> | <%= link_to 'Home', admin_approved_products_path %>]
    </div>
</div>

app/views/products/searched_products.html.erb
<%= render 'notify' %>
<div class="container">
    <div id="page-content">
        <h1 class="text-center mt-4">Search Results</h1>
    </div>
 <%= paginate @products %>
 <div>
 <%= render 'product' %>
 </div>
</div>

app/views/products/show.html.erb
<% if !logged_in? %>
    <p class="text-center bg-warning">You must be logged in to <strong>Buy</strong> any product or <strong>Add any Reviews</strong>.
    Click here to <%= link_to 'Login now', login_path, class: "btn btn-outline-dark" %></p>
<% end %>

<div class="container">
    <h1 class="text-center">Showing a specific product</h1>
    <div class="product-show-info">
            <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
            
                <% @product.pictures.each do |picture| %>
                    <div class="carousel-item  active carousel-slide"">
                    <%= image_tag picture, class: "img-thumbnail d-block w-100" %>
                    </div>
                <% end %>

                <a href="#myCarousel" class="carousel-control-prev" role="button" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </a>
                <a href="#myCarousel" class="carousel-control-next" role="button" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </a>
            </div>
        <div class="product-info">
            <div class="product-details">
                <p class="product-title"><%= @product.title %></p>
                <h4>Rs. <%= @product.price %></h4>
                Description:
                    <p class="text-secondary product-desc"><%= @product.description %></p>
                Ad posted by: 
                    <p class="text-secondary product-desc"><%= @product.user.username %></p>
                Category: <p class="product-desc"><%= link_to @product.category.name, @product.category, class: "text-secondary", style: "text-decoration: none" %></p>

                <p>[<% if logged_in? && @product.user == current_user %>
                    <%= link_to 'Edit this ad', edit_product_path %>
                    | <%= link_to 'Delete',product_path(@product),
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete this Product?" }   %> |
                <% end %> <%= link_to 'Return to products list', admin_approved_products_path %>]</p>

                <div id="<%= dom_id(@product) %>">
                <% if @product.responsed_user_ids.include?(current_user) %>
                    <p>You Have responded</p>
                <% elsif @product.user == current_user %>
                    <%= link_to 'Responded Users', responded_path, class: "btn btn-success" %>
                <% else %>
                    <%= link_to 'Buy Now!!!', buy_product_path(product_id: @product.id, user_id: current_user), method: :patch, class: "btn btn-success" %>
                <% end %>
                </div>
            </div>
           
        </div>
    </div>

    <br/>

    <div class="product-review">

    <div class="product-review-show">
        <% @reviews.each do |review| %>
            <% if review.is_approved == true %>

                <h2>Reviews</h2>
                    <p>
                    <strong>Reviewer:</strong>
                    <%= review.reviewer %>
                    </p>
                                
                    <p>
                    <strong>Review:</strong>
                    <%= review.review_body %>
                    </p>
                    <hr>
            <% end %>
        <% end %>
    </div>
        <h2>Add Reviews</h2>
        <%= render 'reviews/form' %>
    </div>
</div>

app/views/products/toggle_is_approved.js.erb
<% if @product.is_approved == true %>
    $("#<%= dom_id(@product) %> > a").html('true').removeClass('btn-warning').addClass('btn-success')
<% else %>
    $("#<%= dom_id(@product) %> > a").html('false').removeClass('btn-success').addClass('btn-warning')
<% end %>