config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # Product Routes
  get 'admin_approved_products', to: 'products#admin_approved_products'
  get 'products/:id/responded', to: 'products#responded', as: 'responded' #Product owner to see the list of interested buyers
  get '/search_results', to: 'products#searched_products'
  resources :products do
    member do
      patch :buy    # Ajax to handle the buy now button feature
      patch :toggle_is_approved   # Admin to approve or reject the product ad created
    end
    # Reviews routes
    resources :reviews, only: %i[create destroy]
  end
  resources :reviews, only: [:index] do   # Index page for only admin to approve or reject reviews
    member do
      patch :toggle_is_approved
    end
  end

  # Categories
  resources :categories

  # User signup and login
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # User admin
  get 'admin', to: 'users#admin'
  
  # Password Reset
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'

  # Login with google
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  # Conversations and Messages
  resources :conversations do
    resources :messages
  end
end

app/views/layouts/_footer.html.erb
<footer class="text-center text-white fixed-bottom">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: black;">
    © 2020 Copyright:
    <%= link_to 'MyMarket.com', root_path, class: 'text-white footer-link' %>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navigation.html.erb
<header> 
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to 'My Market', root_path, class: 'navbar-brand', id: 'logo' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <%= link_to 'Create new Ad for product', new_product_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Buy', admin_approved_products_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Categories', categories_path, class: 'nav-link' %>
          </li>

          <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'Conversations', conversations_path, class: 'nav-link' %>
          </li>  
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, class: 'nav-link', method: :delete %>
            </li>
          <% else %>
            <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>

          <% if logged_in? %>
              <div class="nav-item dropdown nav-account">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <% if admin? %>
                    (Admin)
                  <% end %>
                  <%= current_user.username %>'s Account
                </a>
                <ul class="dropdown-menu">
                  <% if admin? %>
                    <li><%=link_to "Dashboard", admin_path,class:"dropdown-item" %></li>
                  <% end %>
                  <li><%=link_to "View Profile", user_path(current_user),class:"dropdown-item" %></li>
                  <li><%=link_to "Edit Profile", edit_user_path(current_user),class:"dropdown-item" %></li>
                  <li><%=link_to "All Users", users_path,class:"dropdown-item" %></li>
                  <li><%= link_to "Change Password", password_reset_path, class: "dropdown-item" %></li>
                </ul>
            </div>
        <% end %>
      </div>

    </div>
  </nav>
  <div class="bg-secondary">
    <%= form_tag(search_results_path, method: :get) do %>
      <div class="form-row search-form">
        <div class="col search-form-items">
          <label class="text-light">Title</label>
          <%= text_field_tag "title" %>
        </div>
        <div class="col search-form-items">
          <label class="text-light">Category</label>
          <%= select_tag("category", options_from_collection_for_select(Category.all, "id", "name", params[:category_id]), include_blank: true) %>
        </div>
        <div class="col search-form-items">
          <label class="text-light">City</label>
          <%= text_field_tag "city" %>
        </div>
          
        <%= submit_tag "Search", class: "btn btn-success search-form-button" %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_conversation ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMarket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
</style>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>